services:
  web:
    build: .
    command: gunicorn 'testerRecruting.wsgi' --bind=0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=testerRecruting.settings
      - DB_NAME=testerHelper
      - DB_USER=user
      - DB_PASSWORD=myrootpassword
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=testerHelper
      - MYSQL_USER=user
      - MYSQL_PASSWORD=myrootpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge