version: '3.8'

services:
  nginx:
    image: nginx:1.27.0
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params:ro
      - static_volume:/static
    depends_on:
      - django

  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    command: uwsgi --socket :8001 --module testerRecruting.wsgi --py-autoreload 1 --logto /tmp/mylog.log
    volumes:
      - ./src:/code
      - static_volume:/static
    expose:
      - "8001"
    env_file:
      - ./django/.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  static_volume: